# Generated by Django 5.0.4 on 2024-05-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240501_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        #migrations.AlterField(
        #    model_name='blog',
        #    name='title',
        #    field=models.CharField(max_length=100, unique=True),
        #),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='app.tag'),
        ),
    ]
